# fly.toml app configuration file generated for webshop-api on 2023-04-24T09:35:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "webshop-api"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
