drop table if exists customer;
drop table if exists customer_order_seq;
drop table if exists customer_seq;
drop table if exists customer_order;
drop table if exists item;
drop table if exists item_seq;
drop table if exists order_entry_seq;
drop table if exists order_entry;
create table customer (id bigint not null, first_name varchar(255), last_name varchar(255), ssn varchar(255), primary key (id)) engine=InnoDB;
create table customer_order_seq (next_val bigint) engine=InnoDB;
insert into customer_order_seq values ( 1 );
create table customer_seq (next_val bigint) engine=InnoDB;
insert into customer_seq values ( 1 );
create table customer_order (id bigint not null, date date, customer_id bigint, primary key (id)) engine=InnoDB;
create table item (id bigint not null, name varchar(255), price float(53) not null, primary key (id)) engine=InnoDB;
create table item_seq (next_val bigint) engine=InnoDB;
insert into item_seq values ( 1 );
create table order_entry_seq (next_val bigint) engine=InnoDB;
insert into order_entry_seq values ( 1 );
create table order_entry (id bigint not null, quantity integer not null, item_id bigint, order_id bigint, primary key (id)) engine=InnoDB;
alter table customer_order add constraint FKf9abd30bhiqvugayxlpq8ryq9 foreign key (customer_id) references customer (id);
alter table order_entry add constraint FK5n7w17fxgf4l2bfk6jmg0ldn5 foreign key (item_id) references item (id);
alter table order_entry add constraint FK2g1w98400e049wx49nv437ij8 foreign key (order_id) references customer_order (id);